# -*- coding: utf-8 -*-
"""Hypothesis_Testing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EZ9isoE_c8oGl4saCCrZK63iHBDrtKPt
"""

import pandas as pd
import seaborn as sn
import matplotlib.pyplot as plt
df = sn.load_dataset('taxis')

df.shape

df.info()

df.describe()

df.describe(include='object')

df.isna().sum()

df.isna().sum()/df.shape[0]*100

((df.shape[0]-df.dropna().shape[0])/df.shape[0])*100

df=df.dropna()

df.reset_index(drop='true')

df.color.value_counts()

sn.barplot(x=df.color,y=df.tip,estimator='mean')

sn.barplot(x=df.color,y=df.tip,estimator='std')

sn.histplot(x=df.tip,hue=df.color,kde=True)

#In barplot i have observed that yellow color taxis got more tip than green taxi.It means color effects on tip.
#In histogram i have observed that most people are likely to give small tips like 0 to 5.

#Hypothesis
#H0: distribution of tip of yellow taxi = distribution of tip of green taxi
#H1: distribution of tip of yellow taxi != distribution of tip of green taxi

# Independent T-Test
from scipy import stats
yellow_tip = df['tip'][df['color']=='yellow']
green_tip = df['tip'][df['color']=='green']

t_stat, p_val = stats.ttest_ind(yellow_tip, green_tip)
print("Independent T-Test statistic:", t_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject null hypothesis: Tip differs by Color of taxi")
else:
    print("Fail to reject null hypothesis: No significant tip difference by Color of taxi")

#Payment column

sn.barplot(x=df.payment,y=df.tip, estimator='mean')

sn.histplot(x=df.tip,hue=df.payment,kde=True)

df.payment.value_counts()

from scipy import stats

cash_tip = df['tip'][df['payment'] == 'cash']
credit_card_tip = df['tip'][df['payment'] == 'credit card']

t_stat, p_val = stats.ttest_ind(cash_tip, credit_card_tip)

print(f"Independent T-Test statistic: {t_stat}")
print(f"P-value: {p_val}")

if p_val < 0.05:
    print("\nReject null hypothesis: There is a significant tip difference by payment method.")
else:
    print("\nFail to reject null hypothesis: No significant tip difference by payment method.")

df['pickup_borough'].value_counts()

sn.countplot(x=df['pickup_borough'],palette='Set1')

sn.barplot(x=df.pickup_borough,y=df.tip,estimator='mean',palette='Set3')

sn.histplot(x=df.tip, hue=df.pickup_borough, kde=True, bins=20, palette='Set3')

#Hypothesis
#H0: All categories has same distribution of tip.
#H1: Atleast one category has different distribution of tip.

manhattan_tip=df['tip'][df['pickup_borough']=='Manhattan']
queens_tip=df['tip'][df['pickup_borough']=='Queens']
brooklyn_tip=df['tip'][df['pickup_borough']=='Brooklyn']
bronx_tip=df['tip'][df['pickup_borough']=='Bronx']

# ANOVA Test
f_stat, p_val = stats.f_oneway(manhattan_tip,queens_tip,brooklyn_tip,bronx_tip)
print("ANOVA F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject null hypothesis: All categories has same distribution of tip. ")
else:
    print("Fail to reject null hypothesis: Atleast one category has different distribution of tip.")

from statsmodels.stats.multicomp import pairwise_tukeyhsd
df['pickup_borough'] = df['pickup_borough'].astype(str).astype('category')
tukey_result = pairwise_tukeyhsd(endog=df.tip, groups=df.pickup_borough, alpha=0.05)
print(tukey_result)

df['dropoff_borough'].value_counts()

sn.countplot(x=df['dropoff_borough'],palette='Set1')

sn.barplot(x=df.dropoff_borough,y=df.tip,estimator='mean',palette='Set3')

sn.histplot(x=df.tip, hue=df.dropoff_borough, kde=True, bins=20, palette='Set1')

# Hypothesis
# H0: Mean tip amount is the same across all drop-off boroughs
# H1: At least one borough has a different mean tip amount

manhattan_tip=df['tip'][df['dropoff_borough']=='Manhattan']
queens_tip=df['tip'][df['dropoff_borough']=='Queens']
brooklyn_tip=df['tip'][df['dropoff_borough']=='Brooklyn']
bronx_tip=df['tip'][df['dropoff_borough']=='Bronx']
staten_island_tip=df['tip'][df['dropoff_borough']=='Staten Island']

# ANOVA Test
f_stat, p_val = stats.f_oneway(manhattan_tip,queens_tip,brooklyn_tip,bronx_tip,staten_island_tip)
print("ANOVA F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject null hypothesis: All categories has same distribution of tip. ")
else:
    print("Fail to reject null hypothesis: Atleast one category has different distribution of tip.")

from statsmodels.stats.multicomp import pairwise_tukeyhsd
df['dropoff_borough'] = df['dropoff_borough'].astype(str).astype('category')
tukey_result = pairwise_tukeyhsd(endog=df.tip, groups=df.dropoff_borough, alpha=0.05)
print(tukey_result)

df['pickup_zone'].value_counts()

sn.countplot(x=df['pickup_zone'])

# ANOVA Test
categories = [group['tip'].values for name, group in df.groupby('pickup_zone')]
f_stat, p_val = stats.f_oneway(*categories)
print("ANOVA F-statistic:", f_stat)
print("P-value:", p_val)

if p_val < 0.05:
    print("Reject null hypothesis: Spending Score differs by Region")
else:
    print("Fail to reject null hypothesis: No significant difference by Region")

sn.histplot(df['tip'],kde=True)

sn.histplot(df['passengers'],kde=True)

sn.scatterplot(y=df.tip,x=df.passengers)

# H0: correlation is zero
# H1: there is significant correlation(not zero)
r,p_val=stats.spearmanr(df['tip'],df['passengers'])
print("Correlation:",r)
print("P-value:",p_val)
alpha=0.05
if p_val<alpha:
    print("Reject null hypothesis")
else:
    print("Fail to reject null hypothesis")

sn.histplot(df['fare'],kde=True)

sn.scatterplot(y=df.tip,x=df.fare)

# H0: correlation is zero
# H1: there is significant correlation(not zero)
r,p_val=stats.spearmanr(df['tip'],df['fare'])
print("Correlation:",r)
print("P-value:",p_val)
alpha=0.05
if p_val<alpha:
    print("Reject null hypothesis")
else:
    print("Fail to reject null hypothesis")